# Generated by Django 3.2 on 2021-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpass',
            field=models.CharField(default=2, max_length=50, verbose_name='Gmail Password'),
            preserve_default=False,
        ),
    ]
