# Generated by Django 3.2 on 2021-05-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_gpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
